const Menu = [
  {
    id: 1,
    image: "images/venue1.jpeg",
    name: "Prashant Garden Hall",
    category: "hall",
    price: 25,
    description: "lorem",
  },
  {
    id: 2,
    image: "images/venue2.jpeg",
    name: "Bhosale Garden Hall",
    category: "hall",
    price: 25,
    description: "lorem",
  },
  {
    id: 3,
    image: "images/venue3.jpeg",
    name: "Aishwarya Banquet Hall",
    category: "hall",
    price: 25,
    description: "lorem",
  },
  {
    id: 4,
    image: "images/venue4.jpeg",
    name: "Rajput Lawns",
    category: "lawns",
    price: 25,
    description: "lorem",
  },
  {
    id: 5,
    image: "images/venue5.jpg",
    name: "Kalpataru Karyalay",
    category: "hall",
    price: 25,
    description: "lorem",
  },
  {
    id: 6,
    image: "images/venue6.jpeg",
    name: "Khare Club House",
    category: "hall",
    price: 25,
    description: "lorem",
  },
  // {
  //   id: 7,
  //   image: "images/venue6.jpeg",
  //   name: "Khare Club House",
  //   category: "hall",
  //   price: 25,
  //   description: "lorem",
  // },
  // {
  //   id: 8,
  //   image: "images/venue6.jpeg",
  //   name: "Khare Club House",
  //   category: "hall",
  //   price: 25,
  //   description: "lorem",
  // },
  // {
  //   id: 9,
  //   image: "images/venue6.jpeg",
  //   name: "Khare Club House",
  //   category: "hall",
  //   price: 25,
  //   description: "lorem",
  // },
];

export default Menu;